install: skip

addons:
  ssh_known_hosts: gendercomics.net

before_script:
  - openssl aes-256-cbc -K $encrypted_5b7dc4d89bae_key -iv $encrypted_5b7dc4d89bae_iv -in deploy-key.enc -out deploy-key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy-key
  - ssh-add deploy-key

script:
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy-key
  - ssh-add deploy-key
  - scp -r ../docker deploy@gendercomics.net:/var/gendercomics

deploy:
  - provider: script
    skip_cleanup: true
    script: ssh deploy@gendercomics.net 'cd /var/gendercomics/docker && docker-compose up -d'
    on:
      branches: master

notifications:
  slack:
    rooms:
      - visualitiesofgender:Yvvhzh3sykLIv85to8HSSfKX#builds
    on_success: change
