install: skip

env:
  global:
    secure: dJBKpFTzWBWDncWeEXJi3KLrJ7bEs6Jciu+ALLmJX4rnBAP6+RTFP3kiZzWJjCU24FkijFawbR/GCMuUZDoQUl2M+8LWHKgqqmdTDHdQqZndmyhKqzz3q+tvsNsHl3P4JKbDDZFzT3y5oz0x3IfclW+spGvBS3kdKuKFGkFe8O9aHZf7CMe6zOaihsRwjpz8gurysvQeH33TjIkI8BujBmxOWr+JnwvGEOpjX+XysEev6GWmlLLe3XZgRdLSilg/lRvB//FWv6WUsXOHV8cs2lC86sKzDQBiQTn5RWWp/1+IBvaMhPCGpIbLzsUvVCZsJZmORbIi3Ly5EY6e+jlOewCveisXNORik/MIXirqPbHmzbLCqAm/H/+gDq1l59xCBvqRGiTkg1UDRJhLTgszgjxiSYlLZ2ioDs97Uh7JyEM4aq0/XZQ+Wpoy4K6mx+31mPfG52X+pQdvnaYaExteguEUda8wisK40N3oamEp0kWOuV5sPyD3iTtmgpaiZ4+4Z6/tLLPl2gYUes3pesLnavFCYrzIG85c1H5Y0cCv73GaLEYHOosF7p31rRMKVjuZiUUDYTklLH7iSSWI7UllzNxALywWw7jXXhJNxrxyji291/fHOrte3s3k60Fo2gpGcNmgwGspdjvDORyIcKyHvghM0RSuTO8LEKWFojnPT3s=

addons:
  ssh_known_hosts: gendercomics.net

before_install:
  - openssl aes-256-cbc -K $encrypted_65c1486ae971_key -iv $encrypted_65c1486ae971_iv -in deploy-key.enc -out deploy-key -d

script:
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy-key
  - ssh-add deploy-key
  - scp . deploy@gendercomics.net:/var/gendercomics/docker/

