install: skip

addons:
  ssh_known_hosts: gendercomics.net

before_deploy:
  - openssl aes-256-cbc -K $encrypted_5b7dc4d89bae_key -iv $encrypted_5b7dc4d89bae_iv -in deploy-key.enc -out deploy-key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy-key
  - ssh-add deploy-key

deploy:
  provider: script
  skip_cleanup: true
  script: scp -r ../docker deploy@gendercomics.net:/var/gendercomics && ssh deploy@gendercomics.net 'cd /var/gendercomics/docker && docker-compose up -d --remove-orphans'
  on:
    branch: master

notifications:
  slack: visualitiesofgender:3zAI6z6JJXLeEIaBU49O0Wkr
