version: "3"

services:
  portainer:
    image: portainer/portainer:1.24.0
    environment:
      - HOST
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9000:9000
    labels:
      - traefik.frontend.rule=Host:portainer.${HOST}
      - traefik.port=9000
      - traefik.docker.network=proxy
    networks:
      - proxy

  traefik:
    image: traefik:1.7.21
    container_name: traefik
    environment:
      - HOST
    command: --docker --docker.domain=docker.${HOST} --logLevel=INFO
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik_${HOST}.toml:/traefik.toml
      - ./acme.json:/acme.json
    labels:
      - traefik.frontend.rule=Host:traefik.${HOST}
      - traefik.port=8080
      - traefik.docker.network=proxy
    restart: always

  #loris:
  #  image: bdlss/loris-openjpeg-docker:latest
  #  container_name: iiif-loris
  #  restart: unless-stopped
  #  environment:
  #    - HOST
  #    - IMAGE_LOCATION=/usr/local/share/images
  #  networks:
  #    - proxy
  #  volumes:
  #    - ${IMAGE_LOCATION}:/usr/local/share/images
  #  labels:
  #    - traefik.frontend.rule=Host:iiif.${HOST}
  #    - traefik.port=5004

volumes:
  portainer_data:

networks:
  proxy:
    external: true
