version: "3"

services:
  portainer:
    image: portainer/portainer-ce:2.9.2
    environment:
      - HOST
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9000:9000
    labels:
      - traefik.frontend.rule=Host:portainer.${HOST}
      - traefik.port=9000
      - traefik.docker.network=proxy
    networks:
      - proxy

  traefik:
    image: library/traefik:v1.7.33
    container_name: traefik
    environment:
      - HOST
    command: --docker --docker.domain=docker.${HOST} --logLevel=INFO
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik_${HOST}.toml:/traefik.toml
      - ./acme.json:/acme.json
    labels:
      - traefik.frontend.rule=Host:traefik.${HOST}
      - traefik.port=8080
      - traefik.docker.network=proxy
    restart: always

  mongodb:
    image: mongo:4.2.10
    container_name: mongodb
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rsmongo", "--bind_ip_all" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DATA_DB: ${MONGO_DATA_DB}
      MONGO_DATA_CONFIGDB: ${MONGO_DATA_CONFIGDB}
    volumes:
      - ${MONGO_DATA_DB}:/data/db
      - ${MONGO_DATA_CONFIGDB}:/data/configdb
    networks:
      - proxy
      - data
    ports:
      - 27017:27017
    labels:
      - traefik.enable=false
      - traefik.docker.network=proxy

  elasticsearch:
    image: elasticsearch:${ELK_VERSION}
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ${ES_DATA}:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - data
    depends_on:
      - mongodb

  monstache:
    image: rwynn/monstache:6.7.6
    container_name: monstache
    command: -f ./app/monstache.config.toml
    volumes:
      - ./monstache.config.toml:/app/monstache.config.toml
    ports:
      - "9090:8080"
    depends_on:
      - mongodb
      - elasticsearch
    networks:
      - data
    healthcheck:
      test: "wget -q -O - http://localhost:9090/healthz"
      interval: 10s
      timeout: 30s
      retries: 300
    restart: unless-stopped

  #loris:
  #  image: bdlss/loris-openjpeg-docker:latest
  #  container_name: iiif-loris
  #  restart: unless-stopped
  #  environment:
  #    - HOST
  #    - IMAGE_LOCATION=/usr/local/share/images
  #  networks:
  #    - proxy
  #  volumes:
  #    - ${IMAGE_LOCATION}:/usr/local/share/images
  #  labels:
  #    - traefik.frontend.rule=Host:iiif.${HOST}
  #    - traefik.port=5004

volumes:
  portainer_data:

networks:
  proxy:
    external: true
  data:
    external: true
