defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        users = ["admin:$apr1$7i8yEufb$LlISk/PPdwyHfBgUuHaST1"]
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]
      [entryPoints.http.redirect]
        regex = "^https://www.(.*)"
        replacement = "https://$1"
        permanent = true

[api]
entrypoint="dashboard"

[acme]
email = "michael.litschauer@gmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"

[docker]
domain = "docker.gendercomics.net"
watch = true
network = "proxy"
