defaultEntryPoints = ["http"]

[entryPoints]

  [entryPoints.dashboard]
    address = ":8080"

  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
        regex = "^http://www.(.*)"
        replacement = "http://$1"
        permanent = true

[api]
entrypoint="dashboard"

[docker]
domain = "docker.localhost"
watch = true
network = "proxy"
