# copy docker-compose.yml to digitalocean and run docker-compose

name: docker-compose

on: [push]

jobs:
  deploy_production:
    if: startsWith(github.ref, 'refs/tags/')
    name: production deployment to digitalocean.com
    runs-on: ubuntu-latest
    steps:
      steps:
      - name: check out the repo
        uses: actions/checkout@v2

      - name: copy & run stage
        uses: alinz/ssh-scp-action@master
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          host: ${{ secrets.APP_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          # runs this on remove server
          ssh_before: |
            echo 'PRODUCTION: deploying ${{ github.ref }}'
            cd /var/gendercomics/docker
            ls -lath

          # then upload docker-compose.yml
          scp: |
            ./docker-compose.yml ${{ secrets.DEPLOY_USER }}@${{ secrets.APP_HOST }}:/var/gendercomics/docker

          # then run these commands
          ssh_after: |
            echo 'running docker-compose'
            cd /var/gendercomics/docker
            docker-compose up -d
            echo 'DONE!!!'
